### ISSUE TITLE
Lock fails to release

### ISSUE THREAD

**Issue by MakamuEvans** [dmitry-ivanov/laravel-console-mutex#13]
Hi, nice package.
Am deploying my system on an ubuntu 16.04 server and sometimes the lock fails to release and thus all my tasks just hung like forever and the lock is never released.
What cloud be the problem.
Am using mysql strategy.

template of my code below:
```
namespace App\Console\Commands;

use App\Helpers\Constants;
use App\Jobs\SendBulkSms;
use App\Models\Sms;
use Illuminate\Console\Command;
use Illuminated\Console\WithoutOverlapping;

class QueueBulkSms extends Command
{

    use WithoutOverlapping;

    protected $mutexStrategy = 'mysql';
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'bongatech:queueSms';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Queue Sms for sending';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $this->line("Fetching sms for queue");
        try {
            Sms::where('status', Constants::AWAITING_QUEUE)->chunk(500, function ($messages){
               foreach ($messages as $message){
                   SendBulkSms::dispatch($message->short_message, $message->msisdn, $message->sender_id, $message->id)->onQueue('send_sms');
                   $message->update(['status'=>Constants::QUEUED]);
               }
            });
        }
        catch (\Throwable $throwable){

        }
    }
}
```

**Comment by dmitry-ivanov** [comment]
Regarding the mutex functionality, the code seems fine for me.

I can suggest you few things:

- Provide some logging to the command, so that you would be able to understand what's going on. Maybe your command is still running?

- Do you really have to use `mysql`? Your application deployed on several nodes? If you're deploying to one node (which typically is the case), you can stick with the default `file` strategy.

- Please, check [MySQL documentation](https://dev.mysql.com/doc/refman/5.7/en/locking-functions.html#function_get-lock) for possible reasons of problems with `get_lock()` function.
