### ISSUE TITLE
Command with different params is not working

### ISSUE THREAD

**Issue by moazam1** [dmitry-ivanov/laravel-console-mutex#22]
Hi,

First of all great work. For some reasons Laravel's withoutOverlapping() method didn't work for me because I was seeing same commands overlapping so I opt in to use your package. I think Laravel team should use your package!

I have a command which accepts different arguments i.e. php artisan --action=cleanup or php artisan --action=check-db --table=xyz

Both commands are doing different nature of tasks so your package shouldn't throw error. Is there any chance you can add lock based on the params passed to command?

Also, it would be great if you can add an option to show a warning message instead of throwing exception:  Command is running now! A variable like this in the class will work fine $this->useWarning = true; or have a setting?

**Comment by dmitry-ivanov** [comment]
Hi @moazam1,

Thank you for your kind words! 🙏

There are two different concepts for artisan console commands - [arguments](https://laravel.com/docs/master/artisan#arguments) and [options](https://laravel.com/docs/master/artisan#options).
_(These are actually options in your example, not arguments)_

By default, Laravel Console Mutex [takes into account only arguments](https://github.com/dmitry-ivanov/laravel-console-mutex/blob/9a7c650a71f39d6a00b7e5e373bf27271d0d45ab/src/WithoutOverlapping.php#L109) when it generates the mutex name. But you can easily change that behavior by overriding the `getMutexName()` method (see [readme](https://github.com/dmitry-ivanov/laravel-console-mutex#handle-multiple-commands) for the related example).

_PS:_
> Also, it would be great if you can add an option to show a warning message instead of throwing exception: Command is running now! A variable like this in the class will work fine $this->useWarning = true; or have a setting?

_To be honest, that part of the package has changed several times. Initially, it was simply an info message with `exit()`, then I've used `setCode()` method to override the command's body, then switched to throwing an exception. And I've found that the exception works best because it stops the execution immediately without affecting other integrations that the given artisan console command might have (we check for the mutex in the `initialize()` method of the console command, which could also be used by other integrations). Also, if you're using the [Laravel Console Logger](https://github.com/dmitry-ivanov/laravel-console-logger) - it would be captured in logs for you automatically (you can even get the email notification if you want). Anyways, the package throws a custom exception (`Illuminated\Console\MutexRuntimeException`), so you can always change the way it's handled in your exception handler class._

I hope it helps! 👍

**Comment by moazam1** [comment]
@dmitry-ivanov thank you for the message. I am using Lumen 5.5.x. Due to package dependencies I can't upgrade my Lumen version to see MutexRuntimeException. Right now I am getting RuntimeException. Do you have any suggestion how to prevent this exception? I don't want to put it in the ignore list.

**Comment by dmitry-ivanov** [comment]
@moazam1 I've released [5.5.6](https://github.com/dmitry-ivanov/laravel-console-mutex/releases/tag/5.5.6) for you, and now it throws custom `Illuminated\Console\MutexRuntimeException` on 5.5 as well 👍

**Comment by moazam1** [comment]
Thank you so much!

**Comment by dmitry-ivanov** [comment]
You're welcome! 👍
