### ISSUE TITLE
Mutex redis always throws 'Command is running now!' after force stop

### ISSUE THREAD

**Issue by elygiux** [dmitry-ivanov/laravel-console-mutex#24]
### Versions:

- Package Version: 5.8.*
- PHP Version: 7.4.3
- Redis package "predis/predis": "^1.1"

### Description:

When using redis strategy  $this->setMutexStrategy('redis'); running a command through console and force stopping, cannot run the command again. It always says that the command is running and never clears.

This does not happen with file strategy. 

#### Expected:

After force cancel It should behave same as file strategy. Be cleared after some time

#### Actual:

Always returns 'Command is running now!' after force stop (CTRL+C).

**Comment by dmitry-ivanov** [comment]
That's weird, the package behaves in the same way for all strategies.

The shutdown function [would be registered](https://github.com/dmitry-ivanov/laravel-console-mutex/blob/b93b7fa1e68424696610fa5676e8e58603c570d5/src/WithoutOverlapping.php#L38) and there would be [an attempt to release the lock](https://github.com/dmitry-ivanov/laravel-console-mutex/blob/b93b7fa1e68424696610fa5676e8e58603c570d5/src/WithoutOverlapping.php#L134).

There's also a mechanism for releasing the lock for `predis` in the [underlying library](https://github.com/arvenil/ninja-mutex/blob/82cbb2c56de3aa97b593ae9ba38f76b396f49806/src/Lock/PredisRedisLock.php#L58-L67).

---

_My advice would be - try to debug it a bit more on your end, maybe it doesn't allow you to release lock due to some permissions, or something like that? Anyways, it doesn't seem to be related to the package itself._

**Comment by elygiux** [comment]
I cannot figure out what I'm doing wrong.

If I force stop with CTRL+C, It fails. 

If I try to release the lock manually using $this->releaseMutexLock($mutex); It does not release It.

```
public function releaseLock()
    {
        if ($this->counter > 0) {
            $this->counter--;
            if ($this->counter > 0 ||
                $this->lockImplementor->releaseLock($this->name)) {
                return true;
            }
            $this->counter++;
        }
        return false;
}
```

Because the $this->counter is always 0 when I try to run It again.


If I get here and release the lock manually using $this->client->del($name), It works. 

```
public function releaseLock($name)
    {
        if (isset($this->locks[$name]) && $this->client->del($name)) {
            unset($this->locks[$name]);

            return true;
        }

        return false;
    }
```

So the issue is with acquiring the actual lock here: 

```
protected function initializeMutex()
    {
        $mutex = new Mutex($this);
        if (!$mutex->acquireLock($this->getMutexTimeout())) {
            throw new MutexRuntimeException('Command is running now!');
        }

        register_shutdown_function([$this, 'releaseMutexLock'], $mutex);
    }
```

If we dig a bit deeper, the client->setnx returns 0

```
protected function getLock($name, $blocking)
    {
        if (!$this->client->setnx($name, serialize($this->getLockInformation()))) {
            return false;
        }

        return true;
    }
```

And this happens only when force I force cancel with CTRL+C. If an exception is thrown or If the Command finishes, everything is ok. 

Maybe any ideas ?

**Comment by dmitry-ivanov** [comment]
It seems like there are two different things happen here:
1) When you click CTRL+C - it can't _release_ previously _acquired_ lock.
2) When you re-run the command again - it fails when it tries to re-acquire the lock, _which is correct behavior because of (1)_. _(that `client->setnx returns 0` thing)_

So, I'd suggest digging more into (1) - the process of _releasing_ previously acquired lock when you click CTRL+C.

Check do you even get to the [shutdown function](https://github.com/dmitry-ivanov/laravel-console-mutex/blob/b93b7fa1e68424696610fa5676e8e58603c570d5/src/WithoutOverlapping.php#L134), and what exactly happens after that.

---

_When you get to the [`releaseLock()` method](https://github.com/arvenil/ninja-mutex/blob/82cbb2c56de3aa97b593ae9ba38f76b396f49806/src/Mutex.php#L71-L83) of the `NinjaMutex\Mutex` - I think the `counter` should be `1`, because it had to be incremented when the [lock was acquired](https://github.com/arvenil/ninja-mutex/blob/82cbb2c56de3aa97b593ae9ba38f76b396f49806/src/Mutex.php#L60) in the same iteration._
