### ISSUE TITLE
Laravel 10.x support

### ISSUE THREAD

**Issue by naowas** [dmitry-ivanov/laravel-console-mutex#34]
### Follow these steps:

> Please, note that we have to update versions for everything, not only `illuminate` packages.

1. Update versions in `composer.json` according to Laravel's `composer.json`.
2. Add the newly supported version to `README.md`.
3. Open PR to the `master` branch.

**Comment by dmitry-ivanov** [comment]
Hi @naowas! I'll do an upgrade when I have a bit more time for that, hopefully, this week 👌

**Comment by jerryklimcik** [comment]
@dmitry-ivanov no pressure but is there any update about upgrade? 🙏

**Comment by dmitry-ivanov** [comment]
@jerryklimcik I remember about Laravel 10 updates for all of my packages, but unfortunately due to personal issues - I don't have free time for that now. Will do it as soon as I can.

**Comment by oriceon** [comment]
Hi @dmitry-ivanov. Any news?

**Comment by dmitry-ivanov** [comment]
@oriceon Unfortunately, still don't have time for that now 🤷

Though, I do remember about that.

**Comment by naowas** [comment]
> @oriceon Unfortunately, still don't have time for that now shrug
> 
> Though, I do remember about that.

Any update regarding the issue?

**Comment by Namoshek** [comment]
May I suggest adding one or more additional maintainers (that can review and merge PRs + create releases) to this project, if some volunteers are to be found?

**Comment by rossoman** [comment]
Is the library very necessary. When release under 10 is planned?

**Comment by rossoman** [comment]
check and add a pull request at least

**Comment by dmitry-ivanov** [comment]
@rossoman I understand, but, unfortunately, an open-source doesn't help me to pay the bills. And currently, due to the situation, I have to focus on other things. However, I remember about my packages, and I will upgrade all of them when I have a bit of a slack time.

PS: Also, I think I'll create "goals" on BMC or Patreon to make all necessary updates guaranteed and fast (if I reach them). I think that will help me to maintain packages in a more reliable fashion by using the support of people who need them.

**Comment by neerajsohal** [comment]
Too bad! Will have to go through the pain of forking and installing forked version. 

All the best though with BMC and Patreon. Do inform us :)

**Comment by srd2010** [comment]
For anyone searching for a **quick solution**. 
Since this has not been modified for almost 2 years, i created a fork and released the package with the modifications for Laravel 10.

In case @dmitry-ivanov will continue to update this, i am happy to support.

**In the meantime, you can find the package under:** 
[srd2010/console-mutex](https://packagist.org/packages/srd2010/console-mutex)

**Comment by dmitry-ivanov** [comment]
I've just [released 10.0.0](https://github.com/dmitry-ivanov/laravel-console-mutex/releases/tag/10.0.0) with Laravel 10 support 🎉

Please, consider [supporting further development](https://buymeacoffee.com/dmitry.ivanov).

Thanks!
