### ISSUE TITLE
Mutex file is not deleted

### ISSUE THREAD

**Issue by it-can** [dmitry-ivanov/laravel-console-mutex#4]
I installed your package and when using the file mutex option, after the command is finished the mutex file is still there... When I try to rerun the command it will fail with error:

```
[RuntimeException]
  Command is running now!
```

I used this config setting:

```
protected $mutexStrategy = 'file';

public function getMutexName()
{
    return 'icmutex-test';
}
```

**Comment by it-can** [comment]
I think I have found the problem...

This will **not** release the lock
```
/**
 * Execute the console command.
 */
public function handle()
{
    return $this->info('This is a test!');
}
```

but this will
```
/**
 * Execute the console command.
 */
public function handle()
{
   $this->info('This is a test!');
}
```

**Comment by dmitry-ivanov** [comment]
Hi, @it-can !

Mutex file should NOT be deleted after the command execution. It is the correct behavior.
File locking is done with [flock php function](http://php.net/manual/en/function.flock.php).

I think you can have some issues due to your OS or FS. Is it Windows?
I've tested both of your examples on Unix OS and both works fine.

Anyway, you can use other strategies to make your mutex work, for example, `mysql`.
Just set `$mutexStrategy` property to `mysql` in your command class:
```
class ExampleCommand extends Command
{
    use WithoutOverlapping;

    protected $mutexStrategy = 'mysql';

    // ...
}
```

**Comment by it-can** [comment]
Thanks! I use centos7

**Comment by dmitry-ivanov** [comment]
Hm, so thats strange. Can you provide full command example here, and also php version you're using?

Want to reproduce it.

**Comment by dmitry-ivanov** [comment]
And also the Laravel version please.

**Comment by it-can** [comment]
5.5.4

**Comment by dmitry-ivanov** [comment]
>Can you provide full command example here, and also php version you're using?

**Comment by it-can** [comment]
Mmm it seems to work now... will do some more testing...

**Comment by it-can** [comment]
Ok seems to be a problem with the way I called my command from the controller...

```
Artisan::queue('test:test');
```

I rewrote it using your background helper and now everything works perfect!
